name: build-and-test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup ROS
      uses: ros-tooling/setup-ros@v0.7

    - name: Install dependencies
      run: sudo apt-get update && rosdep install --from-paths src --ignore-src -r -y

    - name: Install Python dependencies
      run: python3 -m pip install -r requirements.txt

    - name: Build the package
      run: colcon build --packages-select behavior_tree

    - name: Run custom tests
      run: python3 src/behavior_tree/behavior_tree/test.py
