name: CI Pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: humble  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up ROS 2
      uses: ros-tooling/setup-ros@v0.2.3
      with:
        required-ros-distributions: ${{ env.ROS_DISTRO }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-colcon-common-extensions
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y

    - name: Build the package
      run: |
        colcon build --event-handlers console_cohesion+

    - name: Run unit tests
      run: |
        colcon test --event-handlers console_cohesion+
        colcon test-result --all
